# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  solution: 'MxNet.Sharp.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactName: 'drop'


steps:
- task: BuildMxNet@2
  inputs:
    command: 'build'
    projects: '$(solution)'

